import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image"
export const metadata:Metadata={
  title:"Home Page",

  description: "Generated by Maryam",}



export default async function Home() {
  //  console.log( await searchParams);
  // console.log(await params);
 

   return (<>
  
    <h1 className='text-5xl underline'>welcome</h1>
  <Image
  className=""
  src="/woman.jpg"
  alt="img"
  width={100}
  height={170}
  /> 
    <Link href="/dashboard">Dash</Link>

    <Link href="/api">APIs</Link>
    <Link href="/services/app-dev">App</Link>
    <Link href="/seo/1">Seo</Link>  
    </>)
};

